version: '3'

services:
  mysql:
    image: mysql:5.7
    volumes:
      - ./mysql/:/var/lib/mysql/
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: spug
      MYSQL_DATABASE: spug
      MYSQL_USER: spug
      MYSQL_PASSWORD: spug
    networks:
      - spug
  spug:
    image: hyr326/spug:latest
    depends_on: 
      - mysql
    ports:
      - "80:80"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: spug      
      DB_USER: spug
      DB_PASSWORD: spug
    networks:
      - spug

networks:
  spug: